galaxy_info:
  author: Matt Baker
  description: Simple role that installs config and packages for network
  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

    # - name: Mint
    #   versions:
    #     - sylvia
    #     - tessa
    #     - tricia
    #     - ulyana
    #     - ulyssa
    #     - uma
    #     - una
    #     - victoria

  galaxy_tags: []

dependencies: []
